version: "3.8"
services:
  frontend:
    container_name: iot-frontend
    volumes:
      - "./frontend:/home/node"
    ports:
      - "80:19006"
    build:
      context: ./frontend
      dockerfile: Dockerfile

  backend:
    container_name: iot-backend
    volumes:
      - "./backend:/home/app"
    ports:
      - "127.0.0.1:8000:8000"
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 8000
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: iot-database
    image: "postgres:14.1-alpine"
    hostname: "iot-database"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 5